var quotes = ["Don't always do things to benefit others, do something that will really bring you pleasure", 
                 "Pay no attention to the 'When' and 'Ifs' of life. Life is much better when it is lived and not yearned after.", 
                 "A real friend enjoys you for you and they enjoy talking with you about things at a deep level.", 
                 "If you live a life based on fear, then you are never going to do anything that you are proud of", 
                 "Tell yourself that it's not about what they think, it's about what you do and whether it's the right thing or wrong thing", 
                 "Take some time to recenter yourself with a walk.",
                 "Life is all about the journey.",
                 "Be constant and strong for your friends and loved ones",  
                 "Be still, understanding, and forever patient with the passing of time and fearless in the face of death.", 
                 "Our desires are filled and, like a colander, the fulfillment empties as soon as it fills up and we need a continuous intake of pleasures.", 
                 "Highest pleasure is the moment when pain ceases", 
                 "Go for the desires that are both natural and necessary", 
                 "Find someone who will stay with you forever", 
                 "Reality - Expectations = Disappointment/Gratitude", 
                 "Repurpose the things we've learned into pieces of new content for others to consume.", 
                 "The difference between a content creator and a consumer is that the content producer sits down and does something about what they've consumed", 
                 "By realizing your negative attributes are much a part of you, we can learn to accept and nurture those parts of ourselves and even turn them into strengths.", 
                 "Life is inherently chaotic", 
                 "Every action you take is a vote for the type of person you wish to become", 
                 "Practice a skill and sell your services on a freelance website like Upwork you can eventually turn that skill into a business.", 
                 "Finding your passion and spending time on it each and every day will make you feel something", 
                 "Minimize your phone applications.", 
                 "Notice those times throughout your day when the first thing you do is check your phone", 
                 "How is your algorithm naturally coded, and what can you do to optimize its outputs.", 
                 "Look at the things you have within your house and think about what you really NEED", 
                 "Reflect upon how you spread your livelihood out and decide whether this space brings you happiness or stares back at you like a void of despair", 
                 "Physical items can be stolen, bought, sold, and replaced but what can never be recovered is time.", 
                 "Next time you miss the mark, fail to meet that deadline, get rejected for that job, turn that failure into a gift.", 
                 "It is not that we have a short time to live, but that we waste a lot of it.", 
                 "Start a side hustle.", 
                 "Learn to diversify your sense of self because not only will it support your well-being but a strong sense of identity will make you a better worker both for yourself and in collaboration with your team.", 
                 "Focus on the present.", 
                 "Don't give up", 
                 "When you are working deep, you are working passionately and you will find meaning in your day-to-day life", 
                 "Put in the work and find a way to be desperate even if there is no reason to be. It’ll fuel your work ethic and make you a more intentional person.", 
                 "Stop talking about the thing, do the thing.", 
                 "Have goals rooted in your sucess", 
                 "Be grateful for what you have and don’t yearn too much for the future.",
                 "Imagine your life being worse and then be grateful it is not.", 
                 "Plan out your tasks and their priorities. After that, however, just do the work", 
                 "Find a better anxiety coping mechanism than anger",
                 "Try working out a little bit each and every day", 
                 "Knowledge is not power. It's only potential power. It only becomes power when we apply it and use it.", 
                 "Dont't become discouraged or defeated by an uncontrollable outcome",
                "The greater the friction, the less likely the habit.",
                "Write your goals down and look at them everyday",
                "Do what you want to do",
                 "Pursue your Passion",
              "Take Action",
                "Think [happy], You’ll be [happy], Think [Your poor], You'll be [poor]",
                "Take out those bad thoughts.",
              "Why did you think of that negative thing?",
              "Take responsibility or your mindset.",
                "Do whatever you can.",
                "Life is not what happens to you but how you react to it.",
              "Everything that happens to you is not your fault, but how you respond to it is.",
              'You are the CEO of your life.',
                'You just picked up your phone to scroll through social media for a few minutes. Here’s a question for you, was it worth it?',
                'Just get your day started off right in whatever way that means to you',
                "You're not failing. You're just in the middle of succeeding.",
                "When you create a difference in someone's life, you not only impact their life, you impact everyone influenced by them throughout their entire lifetime.",
                "Many problems are minor when you solve them right away, but grow into an enormous conflict when you let them linger. As a rule of thumb, fix it now.",
                "It is not necessary to change a person in order to change their behavior. Just change their environment.",
                "Do something instead of nothing",
                "You are not somebody who is easily overcomed by stress. Don't think of yourself that way",
                "By learning to appreciate the small things in your daily life, you'll feel less of a need to go on social media and mindlessly scroll.",
                "FOMO is All About Perspective",
                "Some things can change your life in a slow yet profound manner",
                "Rethink things, Life can only be understood backwards; but it must be lived forwards",
                "It may take you sometime but good is right down the corner.",
                "Take advantage of the advantages you have, else they lose their advantage", 
                "Prioritize your wellbeing over your tasks",
                 "Commitment makes good things better and bad things worse.",
                 "If you're always right, you're not learning.",
                 "People follow incentives, not quote",
                 "The best arguments in the world won't change a single person's mind",
                 "Just because it didn’t work doesn’t mean it was the wrong choice.",
                 "You are tough when your mood is not dependent on your conditions",
                 "I can have a good day with anyone.",
                 "I can work with what I have.",
                 "I can be happy anywhere.",
                 "The right time is right now",
                 "The most important battles must be fought anew each day",
                 "Make mistakes, just don't make them permanent",
                 "If you're unwilling to adapt to the future, you'll justify the past.",
                 "Remove the branches of a thorn bush today and you'll avoid a scrape this year. But next year, you'll face the same problem again.Remove the root of the bush today, and the entire plant will die.Are you solving problems at the branch level or the root level?",
                 "At some level, every experience in life boils down to your interpretation of it but a healthy perspective can lessen the burden, but so can taking action",
                 "How can you renew your sense of childlike wonder?",
                 "When you buy something cheap and bad, the best you’re going to feel about it is when you buy it. When you buy something expensive and good, the worst you’re going to feel about it is when you buy it",
                 "A surefire way to make a bad situation worse is to continue replaying it in your mind.",
                 "What are you willing to give up in order to be great at this?",
              "We are all good at something and I highly recommend you find out exactly what that is and double down on it.",
              "Enjoy the win but don’t gloat or stop what you’re doing for long.",
                 "Laziness may look inviting, but only work gives you true satisfaction.",
              "Don’t let your past mistake define you.",
              "Is taking things so seriously improving my performance?",
                 "You will be interrupted, but you can choose to keep it brief.",
                 "Building habits in the present helps you to do more of what you want in the future",
                 "Focus on things that get you excited longterm",
              "Examine what is said, not the one who says it.",
                 "Most good material is forgotten",
                 "Be great in small ways",
              "Would you rather be right or be happy?",
                 "The hard way is rarely harder in terms of daily effort, but it is often harder psychologically",
                 "Each day is a small lifetime. Live a good life today",
              "What is one step I can take today to help create the outcomes I want in life?",
                 "To tell the truth is often painful. To not to tell the truth is more painful",
                 "Research widely, select carefully.",
                 "Find what you are genuinely interested in",
                 "What is one step I can take today to help create the outcomes I want in life?",
              "What is one previous habit I'd like to reclaim?",
                 "What is one current habit I'd like to let go?",
                 "There are only as many days in the year as you make use of",
                 "Whatever age you are today, your future self would love to be it.",
                 "Lucky opportunities tend to be stumbled upon, not handed out.",
              "Many times in life the question is not whether to do thing or another, but when to emphasize one aspect or another.",
              "Don’t hold onto this anger and anxiety any longer.",
                 "Do not wish away the difficult portions of life. They provide the contrast needed to appreciate the joyful moments.",
                 "Keep ignoring feedback and life will keep teaching you the same lesson.",
                 "A lot of smart people think they’re way smarter than they are, and therefore they do worse than dumb people.",
                 "We all make mistakes",
              "There can be no happiness if the things we believe in are different from the things we do.",
                 "I'm not hurt, I'm healing.",
                 "I'm not losing, I'm learning.",
                "I was not rejected, I was redirected.",
                 "Force yourself to try uncomfortable things",
                 "Win enough to keep progressing. Lose enough to keep learning.",
                 "Don't let people build an identity for you, build your own",
                 "Don't let your intrusive feelings of shame, guilt, anger, and frustration dictate your actions.",
                 "If you don’t forgive yourself now, then when do you plan to?",
              "An investment in self-development pays the highest dividends",
                 "Don’t wait to get something that is ACTUALLY going to improve your workflow, or overall quality of life if you deserve it.",
                 "There is no more profitable investment than investing in yourself. It is the best investment you can make; you can never go wrong with it.",
                 "There will always be reasons to not do something. Be a problem solver, not a problem adder",
                 "The more prepared person usually wins.",
                 "You get credit for action, not preparation.",
                 "Someone with half your IQ is making 10x as you because they aren't smart enough to doubt themselves",
                 "The mind is dead when it is fixed and immovable, The mind is alive when it is flexible and adaptable.",
                 "Keep learning",
                 "It's not the load that breaks you down, it's the way you carry it.",
                 "Do you need to start or finish?",
                 "A car will travel faster not only if you press the accelerator, but also if you remove the speed bumps.",
                 "The ultimate form of preparation is not planning for a specific scenario, but a mindset that can handle uncertainty.",
                 "The question is not, 'Will I succeed?' but rather, 'What should I attempt?'",
                 "Many areas of life that we value most, require a continual commitment.",
                 "A good apology is like antibiotic, a bad apology is like rubbing salt in the wound",
                 "Do I need to spend more time searching for better information or do I need to spend more time acting on the information I already have? ",
                 "contentment is easier to attain than happiness",
                 "fall in love with the process rather than the product",
                 "Have nothing in your houses that you do not know to be useful or believe to be beautiful",
                 "What looks like genius may simply be the byproduct of persistence and variety.",
              "How can I use the negative experiences in my life to drive me?",
                 "What fuel can I draw from my failures?",
                 "What lessons can I take from my grief?",
                 "What insights can I extract from my embarrassments?",
                 "He who angers you, conquers you",
                 "Build a new identity.",
                 "Asking what makes someone successful is like asking which ingredient makes a recipe taste good. It’s not any single ingredient. It is the combination of many ingredients in the right proportions and in the right order—and the absence of anything that would ruin the mixture.",
                 "Start small and become the kind of person who shows up every day.",
                 "Every thought a person dwells upon, whether he expresses it or not, either damages or improves his life",
                 "nobody accomplishes anything significant by accident either.", "The more engaged and interested you are, the more it becomes a craft",
                 "It only takes five minutes to start the cycle.",
                 "What is a change you would benefit from making right now?",
                 "You don’t always get to choose the load, but you can choose how to carry it.",
                 "What I want doesn't exist, so I'll create it",
                 "Think happy, be happy",
                 "Just believe in yourself, even of you dont pretended that you do and someday you will.",
                 "Some want it to happen, some wish it would happen, some make it happen",
                 "Do the best you can until you know better, and when you know better, do better",
                 "You never change things by fighting the existing reality. ",
                 "When something fascinates you, pay attention to the details. ",
                 "If you want to create something but feel it has already been done 1000 times, remember: There is always room for quality.",
                 "The Unit of a Life is a Day. Define your ideal day, then execute each day to make your ideal life",
                 "Take quote from people you want to be.",
                 "You just need to have the courage to eliminate everything that doesn't directly feed what you really want.",
                 "It is nearly impossible to have your best idea the first time you think about something.",
                 "Happiness is the state you enter when you no longer want to change your state.",
                 "The absence of risk produces a kind of boredom which paralyses in a different way from fear, but almost as much.",
                 "the only way we are likely to be any good is to try to be as great as the best.",
                 "You may not control the outcome, but you can influence it.",
                 "We can't expect things perfect in this imperfect world",
                 "Don't trap yourself in the past, its gone and saying 'if only I had done so and so' won't change anything",
                 "Today, is all you have. Yesterday has passed and tomorrow is not promised.",
                 "Dismiss what they have to say. If you desire to please all, you desire the unattainable.",
                 "Don't transform yourself into someone your not.",
                 "In all bad situations, find a positive sign.",
                 "Be gentle, be kind, be forgiving, be merciful.",
                 "What do I want to let go of?",
                 "Your degrees can't take action for you. ",
                 "To be a good listener, you have to stop talking and be interested.",
                 "Where do I want to be in 10 years and What can I do in the next 5 minutes to contribute to that outcome?",
                 "focus on the decisions you can make and the small steps you can take to make a difference.",
                 "Just start",
                 "You have to show up before inspiration will",
                 "Taking action is having hope",
                 "Pogress at your own speed ",
              "People gravitate toward the standard you set, not the standard you request.",
                 "Your job is to fall in love with the process, not grade the outcome.",
                 "The hard way is the fast way.",
                 "The truth of hard work is that it can pay off, but you have to be smart about it.",
                 "By working on a skill that has a delayed income, you can increase your leverage significantly.",
                 "Focus on Your Health",
                 "Delegate, Not only will it save you time, but it will give you the opportunity to reinvest that time into improving the quality of your work",
                 "If you are taking on more tasks, make sure it's done in a controlled manner.",
                 "Prioritize Quality Over Quantity",
                 "If a task can be eliminated, eliminate it.\nIf it can be automated, automate it.\nAnd if it can be delegated, delegate it.",
                 "Oftentimes, people do more things that don’t mean anything.",
                 "Focus on what you can control",
                 "Take the time to think and dream, to question and reconsider.",
                 "The person who consumes from better sources, gets better thoughts",
                 "Even if you don't succeed with this business, you'll still have a good life, so take the risk",
                 "If you want a recipe for unhappiness, spend your time accumulating a lot of money and let your health and relationships deteriorate.",
                 "Stop complaining, start working",
                 "Once hard work becomes a habit, success becomes a lifestyle",
              "Don’t get comfortable",
              "Whatever you are feeling today will fade away.",
              "chose discipline over excuses."
]

function displayQuote() {
  // Calculate the maximum index of the quote quotes array
  var max = quotes.length - 1;
  
  // Generate a random number between 0 and max
  var num = Math.floor(Math.random() * (max + 1));
  
  // Select a random quote from the array using the random number as index
  var thequote = quotes[num];
  
  // Display the selected quote using a message box
    document.getElementById('quote').textContent = thequote;
}
  
// Event Listner
document.getElementById('generate').addEventListener('click', displayQuote);
